### ISSUE TITLE
[FEATURE] 1.19

### ISSUE THREAD

**Issue by Romvnly-Gaming** [DarkKronicle/AdvancedChatBox#11]
**Is your feature request related to a problem? Please describe.**
No work on 1.19.x

**Describe the solution you'd like**
pls make ez commit that updates dep versions 

**Additional context**
N/A

**Comment by DarkKronicle** [comment]
Works for 1.19. Don't know if it works on 1.19.1, but I'm pretty sure it does.

**Comment by Kale-Ko** [comment]
Updating a mod is not as simple as updating the dependency versions

**Comment by Romvnly-Gaming** [comment]
yes it is for some mods, this update wasnt too problematic
