### ISSUE TITLE
[BUG] Tabcomplete after `/` crashes client

### ISSUE THREAD

**Issue by RhythmicSys** [DarkKronicle/AdvancedChatBox#14]
**Describe the bug**
Game crashes when trying to tab-complete commands

**Minecraft Info**
- Minecraft version: `1.19.2`
- AdvancedChatBox `1.19-1.1.5`
- AdvancedChatCore `1.19.1-1.5.6`

**To Reproduce**
type `/`
try to tabcomplete any command
game crashes

**Expected behavior**
tabcomplete would complete the command into chat, and not crash

**Additional context**
[Crash Log 1](https://bytebin.lucko.me/3IWXGTd6Bg)
[Crash Log 2](https://bytebin.lucko.me/mRxjDnFm5W)
[ModPack](https://modrinth.com/modpack/packed)
Originally happened on a 1.19.2 purpur server, reproduced the issue on a single-player creative world

**Comment by RhythmicSys** [comment]
Was able to reproduce with no other mods outside of
`AdvancedChatBox-1.19-1.1.5`
`AdvancedChatCore-1.19.1-1.5.6`
`fabric-api-0.59.0+1.19.2`
`malilib-fabric-1.19.2-0.13.0`
[Crash Log](https://pastes.dev/L6SJK8K2Bm) for that

**Comment by DarkKronicle** [comment]
This will be fixed in the next update, sorry it took so long
