### ISSUE TITLE
[BUG] Crashes after pressing tab

### ISSUE THREAD

**Issue by Rafii2198** [DarkKronicle/AdvancedChatBox#15]
**Describe the bug**
Using autocomplete features will crash the game instantly.

**Minecraft Info**
- AdvancedChatCore: 1.19.1-1.5.6
- AdvancedChatBox: 1.19-1.1.5
- Minecraft: 1.19.2
- Quilt: 0.17.3
- QFAPI: 4.0.0-beta.8+0.59.0-1.19.2
- MaLiLib: 0.13.0

**To Reproduce**
- Type something wrong and press tab
- Type mathematical equation in brackets [] and press tab
- Use any shortcut

Checked only those, probably crashes on all other features.

**Additional context**
Crash report (Again says Fabric, but it is Quilt): https://crashy.net/7YOyZFQUFQqXS6Kkvnps I believe this one is after using math.
And again - using only Core and Box and all modules doesn't change anything, it still crashes.

**Comment by jr0dsgarage** [comment]
The math equation crash happens even if you have the suggestor turned off.

**Comment by Rafii2198** [comment]
An update - Just pressing tab will crash the game, even if you didn't type anything.

**Comment by Kale-Ko** [comment]
I can confirm this, if you press tab it will crash every time no matter your settings or what you have typed. This is the issue I was trying to fix when I tried to update it to 1.19

**Comment by DarkKronicle** [comment]
This will be fixed next update, sorry it took so long
