### ISSUE TITLE
[BUG] ChatBox colors don't change

### ISSUE THREAD

**Issue by Tomasan7** [DarkKronicle/AdvancedChatBox#4]
**Describe the bug**
Setting Chatbox color doesn't work. (the color doesn't change and stays the default one)

**Minecraft Info**
Minecraft information:
- AdvancedChat version 1.3.2-1.18
- AdvancedChatBox,Filters,HUD,Log version 1.1.1

**To Reproduce**
See the attachment video. (neither of the colors work, not just border)

**Expected behavior**
Expected chat box color to be changed.

**Screenshots**
See the attachment video.

**Additional context**
Added a screenshot with the list of all my mods.

https://user-images.githubusercontent.com/47734291/147056592-5e78dcb4-bd4e-405a-9fa1-8b1041d36924.mp4

![explorer_UoZBMD0PrJ](https://user-images.githubusercontent.com/47734291/147056842-9513aa06-5938-4291-8d53-aaab65d6035c.png)

**Comment by DarkKronicle** [comment]
Should be fixed now with an update to core. Let me know if it doesn't
