### ISSUE TITLE
[FEATURE] Ability to append a color code to the start of every message

### ISSUE THREAD

**Issue by GoldOnTop** [DarkKronicle/AdvancedChatBox#6]
I talk in colour text on a server I play on and its kinda annoying having to add color codes infront of every single message I type.

Could you also make it not append a chat colour infront of the message when I type a command.

Thanks.

**Comment by DarkKronicle** [comment]
Adding color codes in front of a message is possible with Advanced Chat Macros, which is currently available in the discord (https://darkkronicle.github.io/discord). I can help you get setup so it won’t do it with commands.

**Comment by DarkKronicle** [comment]
I’m going to close this issue since this is better suited with Macros.
